### ISSUE TITLE
Error using with ssr

### ISSUE THREAD

**Issue by Luncher** [charliekassel/vuejs-datepicker#131]
*code*

```javascript
<template>
  <div class="comment-statis-view">
    <h1>{{ title }}</h1>
    <span>Departure Date：</span>
    <date-picker :value="startDate" @selected="selectStartDate"></date-picker>
    <date-picker :value="endDate" @selected="selectEndDate"></date-picker>
  </div>
</template>

<script>
import Datepicker from 'vuejs-datepicker'

export default {
  name: 'comment-statis-view',

  components: {
    'date-picker': Datepicker
  },

  data () {
    return {
      startDate: new Date(),
      endDate: new Date()
    }
  },

  methods: {
    selectStartDate: function (date) {
      this.startDate = data
    },

    selectEndDate: function (date) {
      this.endDate = data
    }
  }
}
</script>

```

*error* 

```javascript
error during render : /
ReferenceError: window is not defined
    at /home/luncher/vue/BlogAdmin/node_modules/vuejs-datepicker/dist/webpack:/~/vue-style-loader/addStyles.js:14:1
    at module.exports.f (/home/luncher/vue/BlogAdmin/node_modules/vuejs-datepicker/dist/webpack:/~/vue-style-loader/addStyles.js:9:1)
    at module.exports.e.exports (/home/luncher/vue/BlogAdmin/node_modules/vuejs-datepicker/dist/webpack:/~/vue-style-loader/addStyles.js:31:1)
    at Object.<anonymous> (/home/luncher/vue/BlogAdmin/node_modules/vuejs-datepicker/dist/webpack:/src/Datepicker.vue?a680:7:1)
    at t (/home/luncher/vue/BlogAdmin/node_modules/vuejs-datepicker/dist/webpack:/webpack/bootstrap 32c7e875f008b6368f3f:19:1)
```

**Comment by Luncher** [comment]
Excuse me
$isServer where is this variable defined?

**Comment by Luncher** [comment]
@charliekassel

**Comment by charliekassel** [comment]
$ properties are defined in Vue.
https://vuejs.org/v2/api/#vm-isServer

**Comment by Luncher** [comment]
thank you! @charliekassel
