### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by IlhamWahabiGX** [charliekassel/vuejs-datepicker#341]
I'm keep got this (also with npm start) when run the cloned repository 

> vuejs-datepicker@0.9.19 start /home/ilhamwahabi/vuejs-datepicker
> node build/dev-server.js

> Starting dev server...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1354:14)
    at listenInCluster (net.js:1395:12)
    at Server.listen (net.js:1479:7)
    at Function.listen (/home/ilhamwahabi/vuejs-datepicker/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/ilhamwahabi/vuejs-datepicker/build/dev-server.js:84:18)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuejs-datepicker@0.9.19 start: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuejs-datepicker@0.9.19 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ilhamwahabi/.npm/_logs/2017-11-04T18_12_58_928Z-debug.log

**Comment by charliekassel** [comment]
`Error: listen EADDRINUSE :::8080` you already have something using port 8080
